In [4]:
import numpy as np

print(np)
print(np.__version__)

<module 'numpy' from 'C:\\Users\\Moca\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
1.19.2


In [6]:
a = np.arange(15).reshape(3, 5)
print(a)
a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
print(list(a))
print(a.tolist())

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
