# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [1]:
import numpy as np

print(np.zeros((2, 3)))
print(np.empty((2, 3)))
'''
zero產生出的0都是真的0，empty則是接近0非常小的數
要初始化陣列的時候empty比較快
'''

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [2]:
# 記得先 Import 正確的套件



In [3]:
# 參考解答
import numpy as np

a = np.random.rand(2, 3)*100
print(a)
print(a.round())
print(np.round(a))

[[86.71192683 97.88185268 30.83678787]
 [82.3978024  34.86325496 86.74150097]]
[[87. 98. 31.]
 [82. 35. 87.]]
[[87. 98. 31.]
 [82. 35. 87.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [7]:
m = 20
n = 40

a = np.linspace(n, m, 6).reshape(2,3)
print(a)

[[40. 36. 32.]
 [28. 24. 20.]]
