# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [ ]:
# 多維下可設定軸值，定義在array下
# 陣列用，定義在np下
# python內建函式，不限型態

'\nYour Code\n'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [2]:
# 記得先 Import 正確的套件
import numpy as np

In [3]:
A = np.random.random((5, 5))

A = (A-A.min())/(A.max()-A.min())
print(A)

[[0.27159011 0.55276241 1.         0.47838691 0.52506253]
 [0.26263631 0.68945319 0.78094234 0.27310828 0.82719218]
 [0.06586474 0.46591529 0.32042597 0.12391876 0.78554094]
 [0.27108424 0.43073111 0.62566617 0.17519954 0.209967  ]
 [0.80553426 0.48599942 0.59834982 0.70319919 0.        ]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [5]:
B = np.random.random(10)
B[B.argmax()] = -1
print(B)

[ 0.83612628 -1.          0.4043689   0.15458704  0.72502787  0.36160851
  0.68759716  0.76426951  0.69023388  0.68539804]
